name: hikaya
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  shared_preferences: ^2.3.3
  connectivity_plus: ^5.0.2
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  webview_flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.9

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"


# Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  branding: assets/images/branding.png
  color_dark: "#000000"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/branding_dark.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/fonts/



  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
